- name: Deploy Web Server
  hosts: web_servers
  become: true

  tasks:
    - name: Install apache web server
      package:
        name: httpd
        state: present

    - name: copy index.html file
      copy:
        content: |
          <html>
          <head>
          <title>Hello World</title>
          </head>
          <body>
          <h1>Hello World!</h1>
          </body>
          </html>
        dest: /var/www/html/index.html

    - name: Enable apacheservice
      service:
        name: httpd
        state: started
        enabled: true

    - name: Generate self-signed SSL certificate
      openssl_certificate:
        path: /etc/httpd/ssl/apache.crt
        privatekey_path: /etc/httpd/ssl/apache.key
        common_name: "example.com"  # Replace with your domain name
        state: present

    - name: Enable SSL module
      apache2_module:
        name: ssl
        state: present

    - name: Configure Apache SSL virtual host
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^#?<VirtualHost _default_:443>'
        line: '<VirtualHost _default_:443>'
        state: present
        insertafter: '^#?<IfModule mod_ssl.c>'
      notify:
        - Restart Apache

    - name: Enable default SSL virtual host
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^#?</VirtualHost>'
        line: '</VirtualHost>'
        state: present
        insertafter: '</VirtualHost>'
      notify:
        - Restart Apache

    - name: Validate Apache service status
      systemd:
        name: httpd
        state: started

    - name: Validate web server response
      uri:
        url: http://localhost
      register: response

    - name: Validate HTTP to HTTPS redirection
      uri:
        url: http://localhost
        status_code: 301
      register: redirect_response

